version: '3.8'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env

  gideonts:
    image: koen02/gideonts:latest
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - .env:/app.env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gideonts-api.rule=Host(`gideon-api.koen02.nl`)"
      - "traefik.http.routers.gideonts-api.entrypoints=websecure"
      - "traefik.http.routers.gideonts-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.gideonts-api.loadbalancer.server.port=7777"
