name: CICD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cicd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: docker login -u koen02 -p ${{ secrets.DOCKER_PASS }}
           
    - name: Build Docker image
      run: docker build -t koen02/gideonts:latest -t koen02/gideonts:${GITHUB_SHA::8} .
      
    - name: Publish Docker image
      run: docker push koen02/gideonts
      
    - name: Deploy Docker Container Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
